default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: chat_api_development

test:
  <<: *default
  database: chat_api_test

production:
  <<: *default
  database: chat_api_production
